/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Oauth2RouteImport } from './routes/oauth2'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthGameRouteImport } from './routes/_auth/game'

const Oauth2Route = Oauth2RouteImport.update({
  id: '/oauth2',
  path: '/oauth2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGameRoute = AuthGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/oauth2': typeof Oauth2Route
  '/game': typeof AuthGameRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/oauth2': typeof Oauth2Route
  '/game': typeof AuthGameRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/oauth2': typeof Oauth2Route
  '/_auth/game': typeof AuthGameRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/oauth2' | '/game' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/oauth2' | '/game' | '/'
  id: '__root__' | '/_auth' | '/oauth2' | '/_auth/game' | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  Oauth2Route: typeof Oauth2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth2': {
      id: '/oauth2'
      path: '/oauth2'
      fullPath: '/oauth2'
      preLoaderRoute: typeof Oauth2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/game': {
      id: '/_auth/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AuthGameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthGameRoute: typeof AuthGameRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthGameRoute: AuthGameRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  Oauth2Route: Oauth2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
